import pandas as pd
import matplotlib.pyplot as plt
import glob
import os

def main():
    print("=========================================")
    print("      --- GraphMaker 3001 ---")
    print("=========================================")
    print("Scanning current directory for CSV files...")
    
    # 1. Scan directory for CSVs
    csv_files = glob.glob("*.csv")
    valid_files = []

    # Define required columns for format checking to ensure we only plot the right files
    required_columns = ['Sample Name', 'S Parameter', 'S Uncertainty']

    for file in csv_files:
        try:
            # Read first row just to verify headers
            df_test = pd.read_csv(file, nrows=0, on_bad_lines='skip') 
            # Clean up whitespace in column names just in case
            df_test.columns = df_test.columns.str.strip()
            
            if all(col in df_test.columns for col in required_columns):
                valid_files.append(file)
        except Exception:
            continue

    if not valid_files:
        print("-> [ERROR] No valid S-Parameter CSV files found in the current directory.")
        print("   Please ensure your CSV files contain the columns: 'Sample Name', 'S Parameter', and 'S Uncertainty'.")
        return

    print(f"-> Found {len(valid_files)} valid CSV files. Processing data...")

    fig, ax1 = plt.subplots(figsize=(12, 8))

    # Define a colormap to ensure each line is uniquely colored
    cmap = plt.get_cmap('tab10')
    colors = [cmap(i) for i in range(len(valid_files))]

    # 2. Iterate and plot each valid CSV
    for idx, file in enumerate(valid_files):
        print(f"   Plotting file: {file}")
        # We use on_bad_lines='skip' to bypass any corrupted rows (e.g. extra commas generated by the machine)
        df = pd.read_csv(file, on_bad_lines='skip')
        df.columns = df.columns.str.strip()
        
        # Processing
        df['Timestamp'] = pd.to_datetime(df['Sample Name'].astype(str).str.extract(r'(\d{8}_\d{6})')[0], format='%Y%m%d_%H%M%S')
        df['Type'] = df['Sample Name'].astype(str).apply(lambda x: 'Nickel' if 'ANA' in x else 'Zeolite')
        
        # Filter out data points with unusually high error bars (> 0.002)
        df = df[df['S Uncertainty'] <= 0.002]
        
        # Plot Zeolite (Time Series)
        zeolite_df = df[df['Type'] == 'Zeolite'].dropna(subset=['Timestamp']).sort_values('Timestamp')
        
        if zeolite_df.empty:
            print(f"   -> No Zeolite data found in {file}, skipping line plot.")
            continue
            
        start_time = zeolite_df['Timestamp'].min()
        zeolite_df = zeolite_df.copy()
        
        # Standardize time bounds: all graphs start their 'Elapsed Hours' at 0
        zeolite_df['Elapsed Hours'] = (zeolite_df['Timestamp'] - start_time).dt.total_seconds() / 3600.0
        
        label_name = os.path.splitext(file)[0]
        
        # Plot line
        ax1.errorbar(zeolite_df['Elapsed Hours'], zeolite_df['S Parameter'], yerr=zeolite_df['S Uncertainty'],
                     fmt='o-', color=colors[idx], label=label_name, markersize=4, capsize=2, alpha=0.8)

    # 3. Graph Formatting
    ax1.set_xlabel('Elapsed Time (hrs)')
    ax1.set_ylabel('S Parameter')
    ax1.set_title('Zeolite S Parameter Over Time Comparison')
    ax1.legend()
    ax1.xaxis.set_major_locator(plt.MultipleLocator(1))
    ax1.tick_params(axis='x', rotation=45)
    
    # Fixed y-axis range
    ax1.set_ylim(0.54, 0.60)

    # 4. Define custom starting and ending X points
    print("\n=========================================")
    print("          --- X-Axis Bounds ---")
    print("=========================================")
    print("HELPER: The X-axis represents Elapsed Time in hours.")
    print("        0 is the exact start time of the experiment.")
    print("        If you just want to see the whole graph, press ENTER to skip.")
    try:
        x_start = input("\n-> Enter starting X point (Default is 0): ")
        x_end = input("-> Enter ending X point (Default is automatic): ")
        
        if x_start.strip():
            ax1.set_xlim(left=float(x_start))
        else:
            ax1.set_xlim(left=0)
            
        if x_end.strip():
            ax1.set_xlim(right=float(x_end))
    except ValueError:
        print("-> [WARNING] Invalid X bounds entered. Reverting to automatic bounds.")

    # 5. Better Annotation input loop
    print("\n=========================================")
    print("           --- Annotations ---")
    print("=========================================")
    print("HELPER: An annotation draws an arrow pointing to a specific data point")
    print("        with custom text describing it.")
    print("        - X_coord / Y_coord: The exact point on the line the arrow touches.")
    print("        - Text_X / Text_Y: Where the text box itself will hover.")
    print("\nFORMAT TO USE: Text, X_coord, Y_coord, Text_X_coord, Text_Y_coord")
    print("EXAMPLE:       Heating Started, 2.5, 0.57, 2.0, 0.58")
    print("-----------------------------------------")
    print("Type 'done' when you are finished adding annotations.")
    
    while True:
        ann_input = input("\n-> Enter annotation (or 'done'): ")
        if ann_input.lower().strip() == 'done':
            break
        
        parts = [p.strip() for p in ann_input.split(',')]
        if len(parts) == 5:
            try:
                text = parts[0]
                x_c, y_c = float(parts[1]), float(parts[2])
                tx_c, ty_c = float(parts[3]), float(parts[4])
                
                ax1.annotate(
                    text,
                    xy=(x_c, y_c),
                    xytext=(tx_c, ty_c),
                    arrowprops=dict(
                        facecolor='black',
                        arrowstyle='->',
                        lw=1
                    ),
                    fontsize=8,
                    fontweight='bold'
                )
                print(f"   [SUCCESS] Added annotation: '{text}' pointing to ({x_c}, {y_c})")
            except ValueError:
                print("   [ERROR] Invalid coordinates. Please ensure the X and Y coordinates are numbers.")
        else:
            print("   [ERROR] Invalid format. Please provide exactly 5 values separated by commas.")

    print("\n=========================================")
    print("Rendering graph... Close the graph window to exit the script.")
    print("=========================================")
    
    plt.tight_layout()
    plt.show()

if __name__ == "__main__":
    main()